local anm2_data = {
    Animations = {
        Appear = {
            FrameNum = 26,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 58,
                        YScale = 58,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 115,
                        YScale = 85,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 120,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 120,
                        YScale = 80,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 120,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 120,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 20,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 24,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                    },
                },
            },
        },
        Death = {
            FrameNum = 78,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 58,
                        YScale = 58,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 2,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 105,
                        YScale = 95,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 4,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 6,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 12,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 14,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 16,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 18,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 20,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 24,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 26,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 28,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 34,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 36,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 38,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 40,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 42,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 43,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 45,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 47,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 49,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 73,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 140,
                        YScale = 60,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 75,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 77,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                    },
                },
            },
        },
        JumpDown = {
            FrameNum = 64,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 20,
                        YScale = 20,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 20,
                        YScale = 20,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 33,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 5,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -42,
                        XScale = 30,
                        YScale = 170,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 2,
                        XScale = 60,
                        YScale = 140,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 120,
                        YScale = 80,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 80,
                        YScale = 120,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 43,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 56,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 58,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 60,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 62,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = 0,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "false",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 33,
                            Visible = "true",
                        },
                    },
                },
            },
        },
        JumpUp = {
            FrameNum = 15,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 8,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 20,
                        YScale = 20,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 12,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 1,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 3,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 10,
                        XScale = 130,
                        YScale = 70,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 7,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 3,
                        XScale = 50,
                        YScale = 150,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -42,
                        XScale = 30,
                        YScale = 170,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 10,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 13,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 8,
                            Visible = "false",
                        },
                    },
                },
            },
        },
        Taunt = {
            FrameNum = 66,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 2,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 130,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 4,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 115,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 6,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 120,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 8,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 130,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 76,
                        YScale = 124,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 24,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 26,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 28,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 34,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 36,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 38,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 40,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 42,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 44,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 46,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 49,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 52,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 55,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 58,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 60,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 62,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 64,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -58,
                            XScale = 100,
                            YScale = 100,
                            frame = 21,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 62,
                            Visible = "true",
                        },
                    },
                },
            },
        },
        Walk = {
            FrameNum = 45,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 40,
                        YScale = 40,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 40,
                        YScale = 40,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 23,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 1,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 3,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -27,
                        XScale = 88,
                        YScale = 112,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 7,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -48,
                        XScale = 112,
                        YScale = 94,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -42,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -44,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -47,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -44,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -37,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -2,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 130,
                        YScale = 70,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 80,
                        YScale = 120,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 8,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 43,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 1,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 2,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -24,
                            XScale = 100,
                            YScale = 100,
                            frame = 3,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -24,
                            XScale = 100,
                            YScale = 100,
                            frame = 4,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -94,
                            XScale = 100,
                            YScale = 100,
                            frame = 5,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -94,
                            XScale = 100,
                            YScale = 100,
                            frame = 6,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -102,
                            XScale = 100,
                            YScale = 100,
                            frame = 7,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -102,
                            XScale = 100,
                            YScale = 100,
                            frame = 8,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 9,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 10,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 11,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 12,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 13,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 14,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 15,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 16,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 17,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 18,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 19,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 20,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 21,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -80,
                            XScale = 100,
                            YScale = 100,
                            frame = 22,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -20,
                            XScale = 100,
                            YScale = 100,
                            frame = 23,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -20,
                            XScale = 100,
                            YScale = 100,
                            frame = 24,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -54,
                            XScale = 100,
                            YScale = 100,
                            frame = 25,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -54,
                            XScale = 100,
                            YScale = 100,
                            frame = 26,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -44,
                            XScale = 100,
                            YScale = 100,
                            frame = 27,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -44,
                            XScale = 100,
                            YScale = 100,
                            frame = 28,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 29,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 30,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 31,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 32,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 33,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 34,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 35,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 36,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 37,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 38,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 39,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 40,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 41,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 42,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 43,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -48,
                            XScale = 100,
                            YScale = 100,
                            frame = 44,
                            Visible = "true",
                        },
                    },
                },
            },
        },
    },
    Layers = {
        [1] = 1,
        [0] = 0,
    },
    AttributeCombinations = {
        [1] = {
            [1] = {
                Height = 72,
                Width = 120,
                XCrop = 0,
                XPivot = 60,
                YCrop = 0,
                YPivot = 24,
            },
        },
        [0] = {
            [1] = {
                Height = 112,
                Width = 80,
                XCrop = 160,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [2] = {
                Height = 112,
                Width = 80,
                XCrop = 80,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [3] = {
                Height = 112,
                Width = 80,
                XCrop = 240,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [4] = {
                Height = 112,
                Width = 80,
                XCrop = 320,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [5] = {
                Height = 112,
                Width = 80,
                XCrop = 400,
                XPivot = 40,
                YCrop = 224,
                YPivot = 112,
            },
            [6] = {
                Height = 112,
                Width = 80,
                XCrop = 320,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [7] = {
                Height = 112,
                Width = 80,
                XCrop = 0,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [8] = {
                Height = 112,
                Width = 80,
                XCrop = 80,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [9] = {
                Height = 112,
                Width = 80,
                XCrop = 240,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [10] = {
                Height = 112,
                Width = 80,
                XCrop = 160,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
        },
    },
    AttributeDetail = {
        [1] = {
            [1] = {
                st = 0,
                ed = 49,
            },
        },
        [0] = {
            [1] = {
                st = 60,
                ed = 112,
            },
            [2] = {
                st = 66,
                ed = 112,
            },
            [3] = {
                st = 60,
                ed = 112,
            },
            [4] = {
                st = -1111,
                ed = -1051,
            },
            [5] = {
                st = -1223,
                ed = -1163,
            },
            [6] = {
                st = 36,
                ed = 112,
            },
            [7] = {
                st = 80,
                ed = 112,
            },
            [8] = {
                st = 37,
                ed = 112,
            },
            [9] = {
                st = 49,
                ed = 112,
            },
            [10] = {
                st = 45,
                ed = 112,
            },
        },
    },
}

return anm2_data