local anm2_data = {
    Animations = {
        Appear = {
            FrameNum = 26,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 58,
                        YScale = 58,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 115,
                        YScale = 85,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 140,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 130,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 120,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 20,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 24,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                    },
                },
            },
        },
        Death = {
            FrameNum = 78,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 58,
                        YScale = 58,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 2,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 105,
                        YScale = 95,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 4,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 6,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 12,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 14,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 16,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 18,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 20,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 24,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 26,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 28,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 34,
                        Interpolated = true,
                    },
                    {
                        XPosition = 3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = -3,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 36,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 38,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 40,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 42,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 43,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 45,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 47,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 49,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 70,
                        YScale = 140,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 73,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 140,
                        YScale = 60,
                        Rotation = 0,
                        CombinationID = 4,
                        frame = 75,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                    },
                },
            },
        },
        JumpDown = {
            FrameNum = 64,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 20,
                        YScale = 20,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 20,
                        YScale = 20,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 33,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 5,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -43,
                        XScale = 40,
                        YScale = 160,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 1,
                        XScale = 60,
                        YScale = 140,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 80,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 120,
                        YScale = 80,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 80,
                        YScale = 120,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 43,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 120,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 56,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 58,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 130,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 60,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 120,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 2,
                        frame = 62,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -44,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "false",
                        },
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 33,
                            Visible = "true",
                        },
                    },
                },
            },
        },
        JumpUp = {
            FrameNum = 15,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 8,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 20,
                        YScale = 20,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 12,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 1,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 3,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 9,
                        XScale = 130,
                        YScale = 70,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 7,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -30,
                        XScale = 40,
                        YScale = 160,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -60,
                        XScale = 30,
                        YScale = 170,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 10,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -93,
                        XScale = 100,
                        YScale = 160,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 24,
                        YPosition = 47,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 10,
                        frame = 13,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -44,
                            XScale = 100,
                            YScale = 100,
                            frame = 7,
                            Visible = "false",
                        },
                    },
                },
            },
        },
        Taunt = {
            FrameNum = 66,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 58,
                        YScale = 58,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 2,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 130,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 4,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 115,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 6,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 120,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 8,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 130,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 3,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 76,
                        YScale = 124,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 24,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 26,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 28,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = -2,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 34,
                        Interpolated = true,
                    },
                    {
                        XPosition = -1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 36,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 38,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 40,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 42,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 44,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 46,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 49,
                        Interpolated = true,
                    },
                    {
                        XPosition = 1,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 52,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 11,
                        frame = 58,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 60,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 62,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 64,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -62,
                            XScale = 100,
                            YScale = 100,
                            frame = 21,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 62,
                            Visible = "true",
                        },
                    },
                },
            },
        },
        Walk = {
            FrameNum = 45,
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 40,
                        YScale = 40,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 40,
                        YScale = 40,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 0,
                        XScale = 56,
                        YScale = 56,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 23,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 90,
                        YScale = 110,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 1,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 3,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 70,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 9,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -28,
                        XScale = 88,
                        YScale = 112,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 7,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -49,
                        XScale = 112,
                        YScale = 94,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -43,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -45,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -48,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -45,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -38,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 12,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = -3,
                        XScale = 60,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 6,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 130,
                        YScale = 80,
                        Rotation = 0,
                        CombinationID = 7,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 80,
                        YScale = 130,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 8,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 110,
                        YScale = 90,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 95,
                        YScale = 105,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = 0,
                        YPosition = 7,
                        XScale = 100,
                        YScale = 100,
                        Rotation = 0,
                        CombinationID = 1,
                        frame = 43,
                        Interpolated = true,
                    },
                },
            },
            NullAnimations = {
                ID = 1,
                [1] = {
                    Visible = "true",
                    Frames = {
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 0,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -112,
                            XScale = 100,
                            YScale = 100,
                            frame = 6,
                            Visible = "true",
                        },
                        {
                            XPosition = 0,
                            YPosition = -46,
                            XScale = 100,
                            YScale = 100,
                            frame = 23,
                            Visible = "true",
                        },
                    },
                },
            },
        },
    },
    Layers = {
        [1] = 1,
        [0] = 0,
    },
    AttributeCombinations = {
        [1] = {
            [1] = {
                Height = 72,
                Width = 120,
                XCrop = 0,
                XPivot = 60,
                YCrop = 0,
                YPivot = 24,
            },
        },
        [0] = {
            [1] = {
                Height = 112,
                Width = 80,
                XCrop = 160,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [2] = {
                Height = 112,
                Width = 80,
                XCrop = 0,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [3] = {
                Height = 112,
                Width = 80,
                XCrop = 80,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [4] = {
                Height = 112,
                Width = 80,
                XCrop = 240,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [5] = {
                Height = 112,
                Width = 80,
                XCrop = 400,
                XPivot = 40,
                YCrop = 224,
                YPivot = 112,
            },
            [6] = {
                Height = 112,
                Width = 80,
                XCrop = 320,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [7] = {
                Height = 112,
                Width = 80,
                XCrop = 0,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [8] = {
                Height = 112,
                Width = 80,
                XCrop = 320,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [9] = {
                Height = 112,
                Width = 80,
                XCrop = 80,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [10] = {
                Height = 32,
                Width = 32,
                XCrop = 320,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
            [11] = {
                Height = 112,
                Width = 80,
                XCrop = 240,
                XPivot = 40,
                YCrop = 0,
                YPivot = 112,
            },
            [12] = {
                Height = 112,
                Width = 80,
                XCrop = 160,
                XPivot = 40,
                YCrop = 112,
                YPivot = 112,
            },
        },
    },
    AttributeDetail = {
        [1] = {
            [1] = {
                st = 0,
                ed = 49,
            },
        },
        [0] = {
            [1] = {
                st = 64,
                ed = 109,
            },
            [2] = {
                st = 67,
                ed = 112,
            },
            [3] = {
                st = 72,
                ed = 112,
            },
            [4] = {
                st = 64,
                ed = 109,
            },
            [5] = {
                st = -1223,
                ed = -1163,
            },
            [6] = {
                st = 38,
                ed = 112,
            },
            [7] = {
                st = 81,
                ed = 112,
            },
            [8] = {
                st = 60,
                ed = 112,
            },
            [9] = {
                st = 44,
                ed = 109,
            },
            [10] = {
                st = -1111,
                ed = -1051,
            },
            [11] = {
                st = 49,
                ed = 112,
            },
            [12] = {
                st = 45,
                ed = 112,
            },
        },
    },
}

return anm2_data