local anm2_data = {
    Animations = {
        Appear = {
            FrameNum = "26",
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "58",
                        YScale = "58",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "115",
                        YScale = "85",
                        CombinationID = 1,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "120",
                        CombinationID = 2,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "120",
                        YScale = "80",
                        CombinationID = 2,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "120",
                        YScale = "100",
                        CombinationID = 2,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "120",
                        YScale = "90",
                        CombinationID = 2,
                        frame = 20,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 1,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 24,
                        Interpolated = true,
                    },
                },
            },
        },
        Death = {
            FrameNum = "78",
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "58",
                        YScale = "58",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 3,
                        frame = 2,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "105",
                        YScale = "95",
                        CombinationID = 3,
                        frame = 4,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 6,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 12,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 14,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 16,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 18,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 20,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 24,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 26,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 28,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 34,
                        Interpolated = true,
                    },
                    {
                        XPosition = "3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-3",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 36,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 38,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 40,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 42,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 43,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 45,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 47,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 49,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "70",
                        YScale = "130",
                        CombinationID = 3,
                        frame = 73,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "140",
                        YScale = "60",
                        CombinationID = 3,
                        frame = 75,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 4,
                        frame = 77,
                        Interpolated = true,
                    },
                },
            },
        },
        JumpDown = {
            FrameNum = "64",
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "20",
                        YScale = "20",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "20",
                        YScale = "20",
                        CombinationID = 1,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 33,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 5,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-42",
                        XScale = "30",
                        YScale = "170",
                        CombinationID = 6,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "2",
                        XScale = "60",
                        YScale = "140",
                        CombinationID = 6,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 6,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 7,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "120",
                        YScale = "80",
                        CombinationID = 7,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "80",
                        YScale = "120",
                        CombinationID = 3,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 3,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 3,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 43,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 7,
                        frame = 56,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 1,
                        frame = 58,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 1,
                        frame = 60,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 62,
                        Interpolated = true,
                    },
                },
            },
        },
        JumpUp = {
            FrameNum = "15",
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 8,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "20",
                        YScale = "20",
                        CombinationID = 1,
                        frame = 12,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 1,
                        frame = 1,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 7,
                        frame = 3,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "10",
                        XScale = "130",
                        YScale = "70",
                        CombinationID = 7,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 8,
                        frame = 7,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "3",
                        XScale = "50",
                        YScale = "150",
                        CombinationID = 8,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-42",
                        XScale = "30",
                        YScale = "170",
                        CombinationID = 8,
                        frame = 10,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 4,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 4,
                        frame = 13,
                        Interpolated = true,
                    },
                },
            },
        },
        Taunt = {
            FrameNum = "66",
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 1,
                        frame = 2,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "130",
                        YScale = "90",
                        CombinationID = 2,
                        frame = 4,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "115",
                        YScale = "105",
                        CombinationID = 2,
                        frame = 6,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "120",
                        YScale = "100",
                        CombinationID = 2,
                        frame = 8,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "130",
                        YScale = "90",
                        CombinationID = 2,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "70",
                        YScale = "130",
                        CombinationID = 9,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "76",
                        YScale = "124",
                        CombinationID = 9,
                        frame = 22,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 9,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 9,
                        frame = 24,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "95",
                        YScale = "105",
                        CombinationID = 9,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "95",
                        YScale = "105",
                        CombinationID = 9,
                        frame = 26,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 28,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = "2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 30,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-2",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 32,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 33,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 34,
                        Interpolated = true,
                    },
                    {
                        XPosition = "-1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 35,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 36,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 38,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 40,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 42,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 44,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 46,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 49,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 52,
                        Interpolated = true,
                    },
                    {
                        XPosition = "1",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 9,
                        frame = 55,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 9,
                        frame = 58,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "70",
                        YScale = "130",
                        CombinationID = 1,
                        frame = 60,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 1,
                        frame = 62,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 64,
                        Interpolated = true,
                    },
                },
            },
        },
        Walk = {
            FrameNum = "45",
            Loop = "false",
            LayerAnimations = {
                [1] = {
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "40",
                        YScale = "40",
                        CombinationID = 1,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "40",
                        YScale = "40",
                        CombinationID = 1,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "0",
                        XScale = "56",
                        YScale = "56",
                        CombinationID = 1,
                        frame = 23,
                        Interpolated = true,
                    },
                },
                [0] = {
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 0,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "90",
                        YScale = "110",
                        CombinationID = 1,
                        frame = 1,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 7,
                        frame = 3,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "70",
                        YScale = "130",
                        CombinationID = 8,
                        frame = 5,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-27",
                        XScale = "88",
                        YScale = "112",
                        CombinationID = 10,
                        frame = 7,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-48",
                        XScale = "112",
                        YScale = "94",
                        CombinationID = 10,
                        frame = 9,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-42",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 10,
                        frame = 11,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-44",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 10,
                        frame = 13,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-47",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 10,
                        frame = 15,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-44",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 10,
                        frame = 17,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-37",
                        XScale = "95",
                        YScale = "105",
                        CombinationID = 10,
                        frame = 19,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "-2",
                        XScale = "70",
                        YScale = "130",
                        CombinationID = 6,
                        frame = 21,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "130",
                        YScale = "70",
                        CombinationID = 7,
                        frame = 23,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "80",
                        YScale = "120",
                        CombinationID = 3,
                        frame = 25,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 3,
                        frame = 27,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "95",
                        YScale = "105",
                        CombinationID = 3,
                        frame = 29,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 3,
                        frame = 31,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "95",
                        YScale = "105",
                        CombinationID = 1,
                        frame = 37,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "110",
                        YScale = "90",
                        CombinationID = 1,
                        frame = 39,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "95",
                        YScale = "105",
                        CombinationID = 1,
                        frame = 41,
                        Interpolated = true,
                    },
                    {
                        XPosition = "0",
                        YPosition = "8",
                        XScale = "100",
                        YScale = "100",
                        CombinationID = 1,
                        frame = 43,
                        Interpolated = true,
                    },
                },
            },
        },
    },
    AttributeCombinations = {
        [1] = {
            [1] = {
                Height = "72",
                Width = "120",
                XCrop = "0",
                XPivot = "60",
                YCrop = "0",
                YPivot = "24",
            },
        },
        [0] = {
            [1] = {
                Height = "112",
                Width = "80",
                XCrop = "160",
                XPivot = "40",
                YCrop = "0",
                YPivot = "112",
            },
            [2] = {
                Height = "112",
                Width = "80",
                XCrop = "80",
                XPivot = "40",
                YCrop = "0",
                YPivot = "112",
            },
            [3] = {
                Height = "112",
                Width = "80",
                XCrop = "240",
                XPivot = "40",
                YCrop = "112",
                YPivot = "112",
            },
            [4] = {
                Height = "112",
                Width = "80",
                XCrop = "320",
                XPivot = "40",
                YCrop = "112",
                YPivot = "112",
            },
            [5] = {
                Height = "112",
                Width = "80",
                XCrop = "400",
                XPivot = "40",
                YCrop = "224",
                YPivot = "112",
            },
            [6] = {
                Height = "112",
                Width = "80",
                XCrop = "320",
                XPivot = "40",
                YCrop = "0",
                YPivot = "112",
            },
            [7] = {
                Height = "112",
                Width = "80",
                XCrop = "0",
                XPivot = "40",
                YCrop = "112",
                YPivot = "112",
            },
            [8] = {
                Height = "112",
                Width = "80",
                XCrop = "80",
                XPivot = "40",
                YCrop = "112",
                YPivot = "112",
            },
            [9] = {
                Height = "112",
                Width = "80",
                XCrop = "240",
                XPivot = "40",
                YCrop = "0",
                YPivot = "112",
            },
            [10] = {
                Height = "112",
                Width = "80",
                XCrop = "160",
                XPivot = "40",
                YCrop = "112",
                YPivot = "112",
            },
        },
    },
}

return anm2_data